### ISSUE TITLE
What is the difference between training with the two configurations (cub200_promptccd_w_gmp.yaml cub200_promptccd_w_gmp_unknown_C.yaml)

### ISSUE THREAD

**Issue by gangxu822** [Visual-AI/PromptCCD#4]
What is the difference between training with the two configurations (cub200_promptccd_w_gmp.yaml cub200_promptccd_w_gmp_unknown_C.yaml)

**Comment by fcendra** [comment]
Hi there,

In our paper, we experiment with the model in two settings:

- **Known Number of Categories**: When the number of categories is known during discovery in the unlabelled data (main paper, section 3.2). (in the code, we refer this settings with  `%DATASET%_promptccd_w_gmp.yaml` config).
- **Unknown Number of Categories**: When the number of categories is unknown during discovery (main paper, section 3.3).  (in the code, we refer this settings with  `%DATASET%_promptccd_w_gmp_unknown.yaml` config).

Experimenting with the setting where the number of categories is unknown is crucial because, in more realistic scenarios, we often do not have prior knowledge of the number of categories in the unlabelled data.

Best regards, 
Fernando

**Comment by gangxu822** [comment]
thank you

**Comment by gangxu822** [comment]
So the cub dataset can works with both configurations?

**Comment by fcendra** [comment]
Yes. The only the difference is that for the unknown setting, other than discovering the categories from the CUB's unlabelled data, the model are tasked to estimate the number of categories on-the-fly as well.

**Comment by gangxu822** [comment]
okay
